name: Test Playwright Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_APP: ${{ secrets.SECRET_APP }}
      PYTHONPATH: ${{ github.workspace }}
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ secrets.MONGO_DB }}
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongosh --eval "db.runCommand({ ping: 1 })"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/package-lock.json

    - name: Install MongoDB Shell
      run: |
        curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh

    - name: Install Node dependencies
      working-directory: src
      run: npm ci

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        python-version: '3.10'
        activate-environment: test-dragon

    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        cd src
        conda activate test-dragon
        pip install -r requirements.txt
        playwright install --with-deps chromium
        playwright install-deps chromium

    - name: Verify MongoDB Connection
      shell: bash -l {0}
      run: |
        echo "Waiting for MongoDB to be ready..."
        timeout 60s bash -c '
        until mongosh --host ${{ secrets.MONGO_HOST }} --port ${{ secrets.MONGO_PORT }} -u ${{ secrets.MONGO_USER }} -p ${{ secrets.MONGO_PASSWORD }} --eval "db.runCommand({ ping: 1 })" --quiet; do
          echo "MongoDB not ready yet..."
          sleep 2
        done
        '
        echo "MongoDB is ready!"

    - name: Start Express server
      working-directory: src
      run: |
        npm start &
        sleep 10

    - name: Run Playwright tests
      shell: bash -l {0}
      run: |
        conda activate test-dragon
        cd src
        pytest tests/ -v --tb=short -s