name: Test Playwright Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_APP: ${{ secrets.SECRET_APP }}
      PYTHONPATH: ${{ github.workspace }}
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB: DB
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_INITDB_DATABASE: DB
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/package-lock.json

    - name: Install Node dependencies
      working-directory: src
      run: npm ci

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        python-version: '3.10'
        activate-environment: test-dragon

    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        cd src
        conda activate test-dragon
        pip install -r requirements.txt
        playwright install --with-deps chromium
        playwright install-deps chromium

    - name: Verify MongoDB Connection
      shell: bash -l {0}
      run: |
        echo "Waiting for MongoDB to be ready..."
        timeout 60s bash -c '
        until mongosh --eval "db.runCommand({ ping: 1 })" --quiet; do
          echo "MongoDB not ready yet..."
          sleep 2
        done
        '
        echo "MongoDB is ready!"

    - name: Start Express server
      working-directory: src
      run: |
        npm start &
        sleep 10

    - name: Run Playwright tests
      shell: bash -l {0}
      run: |
        conda activate test-dragon
        cd src
        pytest tests/ -v --tb=short -s