name: Test Playwright Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_APP: ${{ secrets.SECRET_APP }}

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_INITDB_DATABASE: DB
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/package-lock.json

    - name: Install Node dependencies
      working-directory: src
      run: npm ci

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        python-version: '3.10'
        activate-environment: test-dragon

    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        cd src
        conda activate test-dragon
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Verify Secrets Availability
      run: |
        echo "Verifying secrets (without exposing sensitive data):"
        echo "MONGO_HOST=${MONGO_HOST}"
        echo "MONGO_PORT=${MONGO_PORT}"
        echo "MONGO_DB=${MONGO_DB}"
        echo "MONGO_USER=${MONGO_USER}"
        echo "BASE_URL=${BASE_URL}"

    - name: Start Express server
      run: |
        npm start &
        sleep 10

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate test-dragon
        echo "Ejecutando pruebas en la carpeta tests/"
        pytest tests/ -v